spring.application.name=trip-plan-practice

spring.datasource.url=jdbc:mysql://localhost:3306/mars_trip
spring.datasource.username=root
spring.datasource.password=dongyang
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=MarsTriPlanSecretKeyMarsTriPlanSecretKey123456
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=1209600000